### ISSUE TITLE
Dead code snippet (draft 20 implementation)

### ISSUE THREAD

**Issue by muhammad-usama-sardar** [Inria-Prosecco/reftls#8]
In [ProVerif modeling of draft 20](https://github.com/Inria-Prosecco/reftls/blob/5a32591014bcadd6cdeecede932c73470b3ec21f/pv/tls-lib-draft20.pvl), no piece of code in any process ever writes to the table `serverSession0_5`. Hence, the [following code snippet](https://github.com/Inria-Prosecco/reftls/blob/5a32591014bcadd6cdeecede932c73470b3ec21f/pv/tls-lib-draft20.pvl#L690-L695) serves no purpose other than adding more confusion to the auditors. 

    (get serverSession0_5(cr,sr,psk,ps,o,m,kc,ks,ems) in
     let nego(v,kkk,hhh,a,pt) = m in
     in (io,(n:bitstring, ad:bitstring));
     let mesg = m_s(v,cr,sr,ps,psk) in
     event ServerSends(v,cr,sr,psk,ps,n,ad,mesg);
     out (io,aead_enc(a,ks,n,ad,mesg)))

This was checked by defining a simple event `test` and placing it between the first and second lines of the above code snippet. Then writing a simple reachability test `query event (test).` confirms that it is not reachable.

**Comment by bruno-blanchet** [comment]
This code aims to model 0.5-RTT messages, which are currently omitted in the model. These messages can be modeled by adding
`     insert serverSession0_5(cr,sr,psk,p,offer,mode,cak,sak,ems);`
just after the line `event PreServerFinished` in the server. Note that, since client authentication is not modeled (as mentioned in the files), the server may establish a session with the adversary, in which case the data messages sent by the server are obviously not secret, so we cannot prove anything about 0.5-RTT messages. That is why we omitted them.
